namespace Refithance.Generator;

internal static class SourceGeneratorHelpers
{
    private const string Header = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Refithance.Generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";

    public const string AttributeFileName = "RefithanceAttribute.g.cs";

    public const string Attribute = Header + @"
namespace Refithance.Generator;

[global::System.AttributeUsage(global::System.AttributeTargets.Interface)]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = ""This code was generated by the Refithance.Generator"")]
public class RefithanceAttribute : global::System.Attribute
{
}
";
}
